---
title: "Untitled"
format: html
editor: visual
---

## Quarto
Jakc regex
"lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_num_matches    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_num_matches    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_num_matches    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_num_matches    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_num_matches    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_num_matches    Unnamed: 0    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_start_idx    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_end_idx    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_cost    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_SEARCH_cost_threshold    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_start_idx    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_end_idx    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_cost    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_SEARCH_cost_threshold    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_start_idx    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_end_idx    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_cost    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_SEARCH_cost_threshold    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_start_idx    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_end_idx    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_cost    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_SEARCH_cost_threshold    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_start_idx    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_end_idx    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_cost    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_start_idx    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_end_idx    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_cost    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_SEARCH_cost_threshold    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_SEARCH_cost_threshold    batch    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_CLEANING_cost_threshold    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_CLEANING_cost_threshold    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_CLEANING_cost_threshold    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_CLEANING_cost_threshold    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_CLEANING_cost_threshold    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_CLEANING_cost_threshold    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?colored"_passed_cleaning    "coloreds?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_passed_cleaning    "lynchings?\W+of\W+(the\W+)?((\w+\W+){1,2})?negro"_passed_cleaning    "negro(e?s)?\W+((\w+\W+){1,2})?((was|were)\W+)?lynch(ed|es|ing)?(\W+|$)"_passed_cleaning    "mob\W+((\w+\W+){1,2})?(hung|hang(ed|ings?|s)|lynch(ed|es|ing)?)"_passed_cleaning    "(murderer|fiend|desperado|brute)\W+((\w+\W+){1,2})?lynch(ed|es|ing)?(\W+|$)"_passed_cleaning
```{r}
# install packages for reading feather files
install.packages("feather")
install.packages("arrow")
library(feather)
library(arrow)
library(tidyverse)
library(tidytext)
# read in the feather file
df <- arrow::read_feather("build_american_stories_dataset/data_by_year/arrow/articles_1922.feather")

df_clean <- df %>%
  # make article lowercase, remove all punctuation and numbers
  mutate(article = str_to_lower(article)) %>%
  # remove punct
  mutate(article = str_replace_all(article, "[[:punct:]]", " ")) %>%
  # remove numbers
  mutate(article = str_replace_all(article, "[[:digit:]]", " ")) %>%
  # remove internal whitespace
  mutate(article = str_squish(article)) 

lynch <- df_clean %>%
  filter(str_detect(article, " lynch |lynching"))

x <- lynch %>%
  mutate(lynch_count = str_count(article, "lynching")) 

df_tokens <- df_clean %>%
  unnest_tokens(word, article) 

df_tokens_count <- df_tokens %>%
  count(word, sort = TRUE) 

df_tokens_count_no_stop <- df_tokens_count %>%
  anti_join(stop_words)

lynch <- df_tokens_count_no_stop %>%
  filter(str_detect(word, "lynch"))

lynch <- df %>%
  filter(str_detect(str_to_lower(article), " lynch "))

lynch_tokens <- lynch %>%
  unnest_tokens(word, article) %>%
  group_by(word) %>%
  count() %>%
  anti_join(stop_words) %>%
  filter(str_detect(word,"lynch"))



```
